### ISSUE TITLE
节点式的MV*系统设计

### ISSUE THREAD

**Issue by otakustay** [ecomfe/yami#1]
### 现状及问题

在一个典型的SPA系统中，当我们在一个页面完成一些特定任务后前往后续页面时，我们往往使用这样的代码：

```javascript
function submit(entity) {
    this.model.save(entity).then(() => this.redirectTo('/next-page'));
}
```

这是一个典型的命令式的代码，在这种实践下，长期以往，事实上我们选择性地忽视了一些事情：

1. 一个函数->一段逻辑的关系与一个页面->整个系统的关系是类似的，整个系统提供的是完整流程的处理，而页面理应是中间的一个节点
2. 基于数据结构的测试、跟踪、管理都要比基于行为更为简单，这一原则应当贯穿在系统的各个方面
3. 程序化描述整个系统的流程拓扑是重要的，但是一直以来并没有被给予足够的重视
4. 页面（节点）的跨系统（流程）的复用变得困难，由于硬编码了逻辑的流转导致不一样的系统不易接入，如果将流转抽象为配置传入页面的逻辑中，则每个页面均要进行处理，导致逻辑的重复堆积

### 核心概念

基于这些理由，我希望创造一种新的模式，其核心理念是：

> 页面是一个处理的节点，拥有完善的“输入”和“输出”的定义，其本身并不关注流程的流转，而是专注于对输入的处理

这一模式下，表现上最大的变化在于：页面将不再直接调用`redirect`等函数进行页间的跳转，而是在特定的时刻抛出（yield）一个结果

一个结果被称为`ActionResult`，此处的`Action`与当前ER框架的`Action`含义并不相同。由于页面作为一个流程节点其结果的产生往往来源于程序或用户的动作，因此其产生的结果被称为“动作结果”，即`ActionResult`

`ActionResult`是一个简单的`{type, state}`的结构，`type`表示当前处理的结果类型，以支持页面的多种输出，而`state`则是输出的数据

在整个MV*框架上，对于任意一个正在执行的页面，监听其输出，针对输出根据用户的配置进行跳转等其它操作

基于此我们可以得到一些优势：

1. 利用`ActionResult`分离了“节点处理”和“节点流转”两方面，让一个页面本身的职责更为纯粹
2. 用户在上层对每个页面不同`type`的`ActionResult`的跳转等配置可以轻松生成整个系统的页面关系拓扑
3. 如果需要针对一个`Action`进行测试，不再需要拙劣地拦截`redirect`等不可穷举的可能性，也不再基于“页面进行此操作后会进行跳转”这一假设（比如从程序跳转换成了`<a>`元素点击，测试用例就可能失效），仅需要检查由页面输出的`ActionResult`，可以进行完全与实现不相关的测试
4. 流程处理和流程流转已经分离，同一个节点可以放入不同的系统，系统可以使用已有的节点如积木一般建立系统，甚至可以将通用性极高的模块（如用户管理、日志控制台等）变成大范围共享的模块（类似rails的某些功能）

### 使用实例

```javascript
// config.js
let config = {
    path: '/user/list',
    use: '/user/List',
    output: {
        redirect(state, {router}) {
            router.redirect(state.url);
        },
        create(state, {router}) {
            router.redirect('/user/create/' + state.userType);
        },
        error(state, {action, application}) {
            let title = `${action.title}发生未知错误`;
            let message = `${state.errorMessage}\n请联系管理员`;
            application.warnGlobalError({title, message});
        }
    }
};

// UserList.js
class UserList {
    createUser(uesrType) {
        this.yieldResult('create', {userType});
    }
}
```

在这一模式下，所有会导致页面切换的行为均应该通过`ActionResult`产生，普通链接的点击也不可避免，因此框架需要监听所有`<a>`元素（技术可行的话包含form提交）并自动调用`yieldResult`产生一个`type`为`redirect`的`ActionResult`，框架层面也应当对这一类型有通用的处理逻辑（调用`router.redirect`）

### 进一步完善

我们可以看到，在这模型下，整个系统变成了一个流，而页面是流中的节点，职责异常分明

在一个良好设计的系统中，可以借鉴函数式的思想，限制每个页面只对输入进行处理，不产生额外的副作用，那么整个系统的健壮性又得以进一步提升，我们并不担心一个页面的行为会持续性地影响其它页面的逻辑

### 细化

1. 从系统层面进行函数式的设计并不容易，需要处理全局变量、`session`等一堆概念
2. 在配置中，针对不同的`ActionResult`的处理函数应该有哪些参数以支持不同的流转

**Comment by srhb18** [comment]
> 框架需要监听所有<a>元素

一些纯粹的新开窗口至wiki、营销中心等的链接，不需要在这个监听的范围内吧

**Comment by otakustay** [comment]
> 一些纯粹的新开窗口至wiki、营销中心等的链接，不需要在这个监听的范围内吧

如果是一个页面的输出，即页面生命周期的终点，就在范围内

如果不是终点，比如产生一个`Dialog`等，则不在此范围内

如何在这种设计下将类似抽屉的这种模式集成进去是一个需要考虑的点，即可能在逻辑上是页面的生命周期的终点，但实际上页面有“复活”这一可能性，可持续存在

**Comment by otakustay** [comment]
当然我还是倾向于框架应该保持简洁的核心，“复活”这一行为可不去支持，抽屉依旧不算页面的终点，属于页面内部行为

**Comment by Exodia** [comment]
我觉得这个和 angular-ui-router比较像，装整个应用映射为一个状态机。 业务确定好各个状态，何时转移到另一个状态，转移到新状态后做什么行为。  而 url 则是状态在 view 层的一个具体映射。

https://github.com/angular-ui/ui-router

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/mmRouter 晒晒我的基于状态机的路由系统

**Comment by otakustay** [comment]
@Exodia @RubyLouvre 我需要去研究一下这两个，比较关键的问题是一些看上去应该由路由负责的但似乎又不会导致页面终结的行为，比如全局的错误弹窗等与此怎么结合

**Comment by xufei** [comment]
路由跟生命周期结合吗？

http://aurelia.io/docs.html#the-screen-activation-lifecycle

**Comment by errorrik** [comment]
节点是什么结构？

**Comment by otakustay** [comment]
在与 @Exodia 等详聊之后，我补充一下我的内容，同时回答楼上各位的疑问和提供的资料

---

### 什么是节点

一个页面（View）是一个节点吗？是的

一个节点就是一个页面吗？并不是

节点是所有符合`(nodeContext) => {nodeContext, type, state}`这一范式的处理逻辑。之所以说这是一个范式，是因为真实的程序表达并非这么简单的输入输出，事实上用接口来表达是这样的：

```
interface Node {
    {Promise.<ActionResult>} execute({NodeContext} nodeContext}
}

class ActionResult {
    {string} type
    {Object} state
    {NodeContext} nodeContext
}

class NodeContext {
    {Object} args
}
```

可以看出，只要有处理能力的都是一个节点，不会仅限于页面。页面是节点的一种，是和种**用户参与其中**的节点

### 为何如此

我们再试着回答几个问题：

1. 一个页面的权限控制这种普遍的需求是否应该由框架提供？
2. 记录用户的各页面访问信息这种不是特别普遍的需求是否应该由框架提供？
3. 每个页面访问前向`Context`中添加当前用户信息这种业务相关度非常高的需求是否应该由框架提供？

基于这些问题，我们可以内置权限控制，可以提供一堆的事件供访问信息记录，但又怎么去实现向`Context`中添加用户信息这种实际业务逻辑呢？

所以我们可以得出一个结论：

> 系统对流程的处理需求是千变万化的，而框架不可能无限提供实现或者提供对应的扩展点

那么在这样的需求下，我试图将所有的处理都抽象为**节点**这一概念，用一个标准的范式来统一节点的描述

### 实际应用

所以现在我们可以有这样的东西：

```javascript
class Permission {
    async execute(nodeContext) {
        if (this.check(nodeContext)) {
            return {type: 'allow', state: null, nodeContext: nodeContext};
        }
        return {type: 'deny', state: null, nodeContext: nodeContext};
    }
}
```

也可以有这样的东西：

```javascript
class Log {
    async execute(nodeContext) {
        console.log(nodeContext);
        return {type: 'pass', state: null, nodeContext: nodeContext}
    }
}
```

所以我们可以这样设计：

```
list(点击某一行修改) -> permission -> log -> form
```

也可以灵活地变成这样，不要日志记录了：

```
list(点击某一行修改) -> permission -> form
```

我们甚至可以用简单的高阶变换把多个东西串起来：

```
let filter = chain(permission, log);
```

所以我们可以用`filter`代替2个节点来使用，省心省力

而将非页面的处理也统一为节点，就导致这不是一个简单的基于状态机的路由就能完成的，也因此楼上诸位提供的这些案例虽然可以满足我预想的一部分需求，但却无法覆盖全部

在不少的框架中，像上面的`permission`和`log`会被定义为中间件。但从处理流程的角度来看，其本质和页面是没有区别的，所以我希望在这边直接给统一起来

### 难点

这个方案的核心是将所有的处理，无论是页面还是程序逻辑，都抽象为一个统一的范式，作为**节点**存在于系统中，但是其一定会带来一些困难：

1. 这个范式是很难设计的，事实上本贴中的这个范式并不完善。比如一个`list`输出`type: 'modify'`后，经过`permission`和`log`等节点，原本的信息会丢失，导致最后不知道应该去`form`
2. 这里有大量的函数式的思想，这会与我们传统的面向对象的设计和实现所冲突，构建大型应用的时候这种精神分裂般的玩法有可能会出现未知的坑

所以如果各位觉得这种是有可能的，我想先试图去细化它，但最终很有可能统一页面节点和非页面节点是走不通的，非页面的节点最终还是归于中间件

但无论如何，页面是一个节点这一点是通顺的，一个MV*框架支持这种开发方式也似乎是可行的

**Comment by otakustay** [comment]
经过一些考证，认为纯节点化的设计不大现实，我关闭此Issue，将路由的终点和中间点分离，中间点用 #3 来解决
